# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"
    config.vm.network "private_network", ip: "192.168.56.11"
    config.vm.hostname = "k8s-worker-01"
  
    config.vm.provider "virtualbox" do |vb|
       vb.name = "k8s-worker-01"
       vb.cpus = 1
       vb.memory = "1024"
    end
     
    config.vm.provision "shell", path: "./../install-docker-kube.sh"
  
    config.vm.provision "shell", inline: <<-SHELL
    
      echo "root password"
      echo "123" | passwd --stdin root
      sed -i 's/^PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
      systemctl reload sshd
  
  
  cat >>/etc/hosts<<EOF
  192.168.56.10 k8s-master-01
  192.168.56.11 k8s-worker-01
  192.168.56.12 k8s-worker-02
  EOF
  
      
    SHELL
  end