kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mariadb-master-pvc
spec:
  storageClassName: mariadb-master-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
