apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-slave-pv
spec:
  storageClassName: mariadb-slave-pv
  capacity: 
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/bitnami/mariadb"