kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mariadb-slave-pvc
spec:
  storageClassName: mariadb-slave-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi